### ISSUE TITLE
how to publish npm registry?

### ISSUE THREAD

**Issue by hyuni** [netPark/node-openalpr#7]
fixed install issue on osx. but not publish npm registry.

asap published

**Comment by gerhardsletten** [comment]
Great, I think the author needs to publish is to npm.

BTW I was trying to look at the mac issues as well, but since I not that into c++ and building I tried a different approach to bundle it within a docker image, but right now I have some silent error.. Will publish it on dockerhub and write a note here I others would like to use it as well

**Comment by gerhardsletten** [comment]
Here is the dockerized express-app [express-openalpr-server](https://github.com/gerhardsletten/express-openalpr-server)

**Comment by kjlaw89** [comment]
New version is out! 1.1.0
